DROP DATABASE IF EXISTS products;

CREATE DATABASE products;

\c products;

CREATE TABLE IF NOT EXISTS products (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  name VARCHAR NOT NULL,
  slogan VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  category VARCHAR NOT NULL,
  default_price VARCHAR(10) NOT NULL
);

COPY products
FROM '/Users/teresalew/HackReactor/sdc_products_data/product.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE IF NOT EXISTS styles (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  productId INT NOT NULL,
  name VARCHAR NOT NULL,
  sale_price VARCHAR(10),
  original_price VARCHAR(10) NOT NULL,
  default_style BOOLEAN NOT NULL,
  CONSTRAINT fk_styles
    FOREIGN KEY(productId)
      REFERENCES products(id)
      ON DELETE CASCADE
);

COPY styles
FROM '/Users/teresalew/HackReactor/sdc_products_data/styles.csv'
DELIMITER ','
CSV HEADER;

CREATE TABLE IF NOT EXISTS features (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  product_id INT NOT NULL,
  feature VARCHAR NOT NULL,
  value VARCHAR,
  CONSTRAINT fk_features
    FOREIGN KEY(product_id)
      REFERENCES products(id)
      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS skus (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  styleId INT NOT NULL,
  size VARCHAR NOT NULL,
  quantity INT NOT NULL,
  CONSTRAINT fk_skus
    FOREIGN KEY(styleId)
      REFERENCES styles(id)
      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS photos (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  styleId INT NOT NULL,
  url VARCHAR NOT NULL,
  thumbnail_url VARCHAR NOT NULL,
  CONSTRAINT fk_photos
    FOREIGN KEY(styleId)
      REFERENCES styles(id)
      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS related (
  id INT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  current_product_id INT NOT NULL,
  related_product_id INT NOT NULL,
  CONSTRAINT fk_related
    FOREIGN KEY(current_product_id) REFERENCES products(id)
    ON DELETE CASCADE
);

COPY features
FROM '/Users/teresalew/HackReactor/sdc_products_data/features.csv'
DELIMITER ','
CSV HEADER;

COPY photos
FROM '/Users/teresalew/HackReactor/sdc_products_data/photos.csv'
DELIMITER ','
CSV HEADER;

COPY skus
FROM '/Users/teresalew/HackReactor/sdc_products_data/skus.csv'
DELIMITER ','
CSV HEADER;

COPY related
FROM '/Users/teresalew/HackReactor/sdc_products_data/related.csv'
DELIMITER ','
CSV HEADER;

